Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.synced_folder "./data", "/home/vagrant/data"
    config.vm.provision "file", source: "./confs", destination: "/home/vagrant/"
    #config.vm.provision "file", source: "./scripts", destination: "/home/vagrant/"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    config.vm.define "Soherba" do |soherba|
      soherba.vm.hostname = "Soherba"
      soherba.vm.network "private_network", ip: "192.168.42.110"
      soherba.vm.provision "shell", path: "./scripts/master.sh"
      soherba.vm.provision "shell", path: "./scripts/runImages.sh",privileged: false
    end
    config.trigger.before :up do |trigger|
        trigger.name = "create data folder"
        trigger.info = "create data folder before running"
        trigger.run = {path: "./scripts/mkdir.sh"}
    end
    
end