Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.provision "file", source: "./confs", destination: "/home/vagrant/"
  config.vm.define "oherbaS" do |oherbaS|
    oherbaS.vm.hostname = "oherbaS"
    oherbaS.vm.network "private_network", ip: "192.168.42.110"
    oherbaS.vm.provision "shell", path: "./scripts/install.sh"
    oherbaS.vm.provision "shell", path: "./scripts/setup.sh"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4098"
      vb.cpus = "4"
    end
  end
end
#wait for gitlab 5-8 min
# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo